using System.Drawing;
using System.Windows.Forms;
using DevExpress.XtraGrid.Views.Grid.ViewInfo;
using Logic.Models;
using Logic.ViewModels;

namespace TimeSheets
{
	public partial class TimeSheetGrid : UserControl
	{
		private GridViewModel Model { get; set; }

		public TimeSheetGrid()
		{
			InitializeComponent();
		}

		public void InitializeModel(TimeSheetsModel model)
		{
			Model = new GridViewModel(model);
			
			// This line of code is generated by Data Source Configuration Wizard
			_gridControl.DataSource = Model.EditEntries;
			Model.Subscribe(UpdateUI);
		}

		private void _gridView_RowCellClick(object sender, DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs e)
		{
			GridHitInfo hitInfo = _gridView.CalcHitInfo(new Point(e.X, e.Y));
			if (!hitInfo.InRow || e.Button != MouseButtons.Left)
			{
				return;
			}

			var entry = _gridView.GetRow(_gridView.FocusedRowHandle) as ActivityModel;
			if (entry != null)
				Model.SelectionChangedCommand.Execute(entry);
		}

		private void UpdateUI()
		{
			_gridControl.Refresh();
		}

		/// <summary> 
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				Model.Unsubscribe(UpdateUI);
				components.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}
